language: rust
sudo: false
rust: nightly

install: cargo install mdbook
script: cd reference && mdbook build && mdbook test
env:
  RUSTINFRA_DEPLOY_DIR: reference/book
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml
